name: dartz
version: 0.0.10
homepage: https://github.com/spebbe/dartz
description: Functional Programming in Dart, heavily inspired by scalaz.
author: Bj√∂rn Sperber <spebbe@gmail.com>

environment:
  sdk: '>=1.13.0 <2.0.0'

dev_dependencies:
  test: "^0.12.4+5"
  propcheck: "^0.5.1"
